# This is a basic workflow to help you get started with Actions

name: API POI CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:    
      - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:    
      - 'apis/poi/**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x

      - name: Restore dependencies
        run: dotnet restore apis/poi/poi.sln

      - name: Build
        run: dotnet build --no-restore apis/poi/poi.sln
      
      - name: Unitests
        run: dotnet test --no-build --verbosity normal -r testresults --logger "trx" apis/poi/poi.sln
        
